### ISSUE TITLE
Cannot generate unit test mocks when excluding generic dependency

### ISSUE THREAD

**Issue by jamie-burns** [Bungalow64/SlowFox#26]
I have a class where I'm injecting ILogger<MyClass> as a dependency:

```csharp
[InjectDependencies(typeof(ILogger<MyClass>), typeof(IOtherDependency))]
public partial class MyClass
{

}
```

I've created a unit test class for this, and injecting the mocks but excluding the ILogger dependency:

```csharp
[InjectMocks(typeof(MyClass))]
[ExcludeMocks(typeof(ILogger<MyClass>))]
public partial class MyClassTests
{

}
```

I've getting this warning:

Warning	SFMKX001	Couldn't generate the mocks for object 'MyClassTests'.  Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.GenericNameSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax'.    at SlowFox.Core.GeneratorLogic.UnitTestMocks.Generators.BaseMockGenerator.<>c__DisplayClass18_2.<Execute>b__5(TypeOfExpressionSyntax p)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SlowFox.Core.GeneratorLogic.UnitTestMocks.Generators.BaseMockGenerator.Execute(GeneratorExecutionContext context).	MyProject.Tests	C:\MyProject\MyClassTests.cs	8	Active

**Comment by jamie-burns** [comment]
This has been fixed as part of v1.0.1
